create basic ui for sign up
mudrila/fin-plan pull request #10
Opened 2024-09-10 11:05 UTC by Artemh59

2024-09-10 11:37 UTC, mudrila requested changes
Bunch of design / implementation suggestions

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +      <Card variant="outlined" sx={{ p: 3 }}>
I'd suggest putting form title into `CardHeader` instead of keeping that separate from the card

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +    <SignUpContainer>
Which probably means we can remove `SignUpContainer` as a whole and move outlining page markup, which brings page's content to the center of the screen into `layout.tsx`

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +          <Stack spacing={2}>
Then instead of `Stack` we can use `CardContent`

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +        <Box
And then we could remove this quite redundant `Box` element and style `Card` properly, rendering it as `form` element and passing `onSubmit={handleSubmit}` into `Card`

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +          <Button
And the button will go into `CardActions` component which will visually separate `Card`'s content / form fields from the "form actions"

2024-09-10 11:37 UTC, mudrila commented on src/app/sign-in/page.tsx
> +
Let's add some basic metadata 
```
import type { Metadata } from 'next'; // verify correctness of the import statement

export const metadata: Metadata = {
  title: 'Sign Up | Fin-Plan',
}
```

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-container.tsx
> +  children: React.ReactNode;
Purely matter of personal preference, but if you don't mind - let's keep desctructured imports instead of accessing concrete values / types from global object.
So instead of `children: React.ReactNode` with can do `children: ReactNode`
On top of that - since there's no any extra props - we can just use `PropsWithChildren`

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +  const validateForm = () => {
Instead of validating the form upon submission - let's perform validation as user types.

This means we need to create bunch of `handle...Change` which will perform value validation, handle error display for specific field and setting value for the specific field.
This will provide instant feedback to the user on correctness of the form

2024-09-10 11:37 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +            <TextField
Also, this input should contain visual representation of password strength as user types.
I'm envisioning something like 5 boxes. Initially they're grey. When you start typing password - each box represents whether certain part of validation succeeded. The more boxes you "close" - the more color transitions from "error.dark"  -> "error.main" -> "warning.main" -> "success.light" -> "success.main"
Let me know if you need further guidance or design reference

2024-09-10 11:56 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +    setShowPassword(!showPassword);
Another nit-pick, which is rather how react updates state tree. When you want to "toggle" boolean value - you should use `prevState` from the `set...` callback

So this should be
```
const handleClickShowPassword = () => {
  setShowPassword(prevState => !prevState);
}
```

Not as much critical in this specific case, but when you have multiple elements that are toggling same state or relying on same state - you'll start noticing inconsistencies

2024-09-11 08:24 UTC, mudrila requested changes
Couple more changes sir, but we're almost there!

2024-09-11 08:24 UTC, mudrila commented on src/app/sign-in/layout.tsx
> +export default function SignInLayout({ children }: PropsWithChildren) {
This is `SignUp` layout though 😄 
Please, rename it and move this layout file into `src/app/(auth)/layout.tsx` - I'm quite sure we'd want to reuse same layout across Sign In / Sign Up / Forgot Password pages

2024-09-11 08:24 UTC, mudrila commented on src/app/sign-in/page.tsx
And then this file should be moved into `src/app/(auth)/sign-up/page.tsx`

2024-09-11 08:24 UTC, mudrila commented on src/app/sign-in/layout.tsx
> +      maxWidth="xs"
Let's make it slightly bigger - `maxWidth="sm"`

2024-09-11 08:24 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +          {['', 'Very Weak', 'Weak', 'Medium', 'Strong', 'Very Strong'][passwordStrength]}
Let's move this array to some `const` out of context of this component, in the same file but just outside of component code. 

```
const PASSWORD_STRENGTH_DESCRIPTIONS = ['', 'Very Weak', 'Weak', 'Medium', 'Strong', 'Very Strong']
```
And then instead of inline index usage - let's make it little more clear through assigning this value to variable

```
const passwordStrengthDescription = useMemo(() => PASSWORD_STRENGTH_DESCRIPTIONS[passwordStrength], [passwordStrength])
```

2024-09-11 08:24 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +          Password strength:{' '}
Then we can use string literal here to avoid text node splitting in HTML:
```
{`Password strength: ${passwordStrengthDescription}`}
```

2024-09-11 08:25 UTC, mudrila commented on src/app/sign-in/layout.tsx
> +export default function SignInLayout({ children }: PropsWithChildren) {
FYI - this `(auth)` thingy called "route group" which allows you to apply shared `layout` for set of `routes` without affecting URL structure:
https://nextjs.org/docs/app/building-your-application/routing/route-groups#organize-routes-without-affecting-the-url-path

2024-09-11 09:13 UTC, mudrila requested changes
More changes sir

2024-09-11 09:13 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +          onChange={e => handleEmailChange(e.target.value)}
Please modify `handleEmailChange` so that it expects `event` being passed there directly. This is to avoid creating one more anonymous function during each render. Just a good practice to use

2024-09-11 09:13 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +          onChange={e => handlePasswordChange(e.target.value)}
Same here - `onChange={handlePasswordChange}`

And then `const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>) => ...`

2024-09-11 09:13 UTC, mudrila commented on src/app/components/sign-up-form.tsx
> +          onChange={e => handleConfirmPasswordChange(e.target.value)}
Same here

2024-09-11 09:13 UTC, mudrila commented on src/app/components/sign-up-form.tsx
Please, move this file into `src/components/organisms/Forms/SignUp/SignUp.tsx`.

With this we'll introduce 3 changes into our naming conventions:
1. Following "atomic design principles" - don't worry about digging into that right now, we'll learn those principles in further PRs.
2. Everything that lyes under `src/app` - exclusively for routing, server components and shared layout. All the presentational / client components are going under `src/components`
3. File naming convention - files with components should be called exactly the way as components called. It doesn't mean we should be creating separate file for each small component, if that's used only in other bigger component - we'll discuss these best practices later on.

2024-09-11 09:13 UTC, mudrila commented on src/app/(auth)/sign-up/page.tsx
> +
Oops, seems like `export const metadata` got lost - please add it back

2024-09-11 09:26 UTC, Artemh59 commented
Oh, I made a lot of mistakes, sorry, next time I'll try to write better code🙂

2024-09-11 09:29 UTC, mudrila commented
> Oh, I made a lot of mistakes, sorry, next time I'll try to write better code🙂

@Artemh59 Those are not mistakes - PR review is not an act of "finding your mistakes", but rather a way to align for us on best-practices and implementation details.
Your code is quite good - keep up the good work sir!

2024-09-11 19:03 UTC, mudrila requested changes
Code-wise looks good!
Just need couple tweaks on files location. 
1. `src/components/sign-up-form.tsx` -> `src/components/organisms/Forms/SignUpForm/SignUpForm.tsx`
2. `src/app/(auth)/sign-up/layout.tsx` -> `src/app/(auth)/layout.tsx`

2024-09-11 19:03 UTC, mudrila commented on src/app/(auth)/sign-up/layout.tsx
This layout file should be located at following path: `src/app/(auth)/layout.tsx` - then it will be re-used across other pages that will be placed within `src/app/(auth)` folder
https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates#nesting-layouts

2024-09-12 00:55 UTC, mudrila approved these changes
Great job sir!

2024-09-12 00:56 UTC, merged