Set up `prisma` and connect to `Vercel`'s `PostgreSQL` DB Storage
mudrila/fin-plan pull request #14
Opened 2024-09-11 17:58 UTC by Artemh59

2024-09-11 18:11 UTC, Artemh59 commented
I thought the problem was that the Prisma package was not installed, but now I don't know what happened.
And I probably done all to connect vercel (I hope) but I'm not sure, that's why I didn't make new migrations

2024-09-11 19:11 UTC, mudrila requested changes
Gave you some direction on where to dig - let me know if you'll need some further assistance

2024-09-11 19:11 UTC, mudrila commented on prisma/schema.prisma
> +generator client {
Essentially, I don't see any models in the `schema` - that's probably the source of an issue
Try adding models that are described in `NextAuth` documentation and run

```
npx prisma migrate --name add_user_session_models
```

2024-09-11 19:11 UTC, mudrila commented on package.json
> +    "postinstall": "prisma generate"
Let's slightly change scripts. Instead of `"postinstall": "prisma generate"` - please, add following scripts

```
"prisma:format": "npx prisma format",
"prisma:generate": "npx prisma generate",
"prisma:migrate": "dotenv -e .env.local -- npx prisma migrate dev",
"postinstall": "npm run prisma:generate"
```

2024-09-11 19:11 UTC, mudrila commented on package.json
>    "dependencies": {
AFAIK - we need to have `prisma` package in `devDependencies`. Just add it there manually:
```
"prisma": "^5.19.1"
```

And run `npm install`

2024-09-11 19:11 UTC, mudrila commented on prisma/schema.prisma
> +generator client {
FYI - the link to `NextAuth` docs with required minimum schema: https://next-auth.js.org/v3/adapters/prisma#setup

2024-09-12 00:58 UTC, mudrila approved these changes
Great!

2024-09-12 01:00 UTC, merged