Set up `NextAuth` for managing user's session
mudrila/fin-plan pull request #17
Opened 2024-09-12 08:07 UTC by Artemh59

2024-09-12 18:29 UTC, mudrila requested changes
Please move `auth.ts` and `prisma.ts` into `src/utils`
Also, I don't see necessary routes setup - please add `src/app/api/auth/[...nextauth]/route.ts` with exporting `GET` and `POST` handlers from there

2024-09-12 18:29 UTC, mudrila commented on package.json
> +    "@auth/core": "^0.34.2",
Not quite sure - why do we need this package? Seems like redundant to have it explicitly added to the dependencies - sub-packages needed for us are coming with `next-auth`

2024-09-12 18:29 UTC, mudrila commented on prisma.ts
Please, put this file into `src/utils/prisma.ts` - this is part of the application source code, so should be places within `src` folder

2024-09-12 18:29 UTC, mudrila commented on auth.ts
Similarly here - please put it into `src/utils/auth.ts`

2024-09-13 01:30 UTC, mudrila requested changes
Last comment and we should be good, sir

2024-09-13 01:30 UTC, mudrila commented on src/app/api/auth/[...nextauth]/route.ts
> +const handler = NextAuth({providers: []});
Instead of re-initializing `NextAuth` here - we should be importing already initialized handlers 

```
import { handlers } from '@/utils/auth';
export const { GET, POST } = handlers;
```

2024-09-13 08:21 UTC, Artemh59 commented
I had an error: (node:30240) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

I deleted it, but if we need it I can return it, and I don't understand what happened  in Vercel, I also tried to rewrite auth file, but it didn't help

2024-09-13 11:55 UTC, mudrila approved these changes
@Artemh59 The problem was due to `next-auth` v4, but configuration we are targetting is for v5 - I updated packages and added necessary configs and now everything works. Make sure to pull env variables from Vercel

2024-09-13 11:55 UTC, merged