Feature/#23 implement budget account entity creation
mudrila/fin-plan pull request #33
Opened 2024-09-27 14:21 UTC by Artemh59

Closes #23

2024-10-01 08:57 UTC, mudrila requested changes
Quite a bit of stuff to do sir - but pretty good start sir!

2024-10-01 08:57 UTC, mudrila commented on prisma/schema.prisma
> +  id           String            @id @default(uuid())
Let's use `cuid` to keep ID format consistent with `User` model - apologies for the confusion in the ticket description

2024-10-01 08:57 UTC, mudrila commented on prisma/schema.prisma
> +  monthlyLimit Decimal           @default(0)
Let's also add `currentBalance` field 
`currentBalance Decimal @default(0)`

2024-10-01 08:57 UTC, mudrila commented on prisma/schema.prisma
> +enum BudgetAccountType {
Let's also add `Goal` entry into `BudgetAccountType` - this will represent certain financial goal and will work slightly differently comparing to other types

2024-10-01 08:57 UTC, mudrila commented on src/app/api/budgetAccount/create/route.ts
> +    return NextResponse.json({ message: 'Your account created!' });
Let's just return `success: true` instead of message - it will be responsibility of FE side to decide which message to display in case of successful creation - there should be just clear indication that everything went well

2024-10-01 08:57 UTC, mudrila commented on src/app/api/budgetAccount/create/route.ts
> +      errorMessage: 'Please check our data',
Let's rephrase it to `errorMessage: 'Unexpected error happened while creating budget account.'`

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +    const formData = new FormData(event.currentTarget);
Let's use react controlled state / controlled inputs instead of native event DOM API

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +    toast.message('Hand tight - we are creating budget account for ya...');
I'd suggest `toast.info` - also we need to dismiss this toast once we've got response from the API route.

```
const loadingToastId = toast.info('...');

// blah blah making request

const responseData = await response.json();
toast.dismiss(loadingToastId);

if (responseData.success) {
  toast.success('Hell fucking yeah dude, it works!', { duration: 5000 });
} else if (responseData.errorMessage) {
  toast.error(responseData.errorMessage)
} else {
  toast.error('Something went wrong...');
}

```

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +    const formData = new FormData(event.currentTarget);
Also please add `useTransition` usage to visualize loading state for the user

2024-10-01 08:57 UTC, mudrila commented on src/constants/content.ts
> +export const accountTypes = ['Income', 'Debt', 'SpendingCategory', 'Credit', 'Debit'] as const;
You can form this array via `Object.values(BudgetAccountType) as const`

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +          <TextField
Let's explicitly use `Select` component https://mui.com/material-ui/react-select/

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +        <DialogTitle>Create Account</DialogTitle>
Let's be explicit - `Create Budget Account`

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +          <DialogContentText>To create an account, please enter your data here.</DialogContentText>
Don't think we need this description here - title should be sufficient, let's save some space :)

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
Let's rename this file to `BudgetAccountForm`, but keep it under `BudgetAccount` folder

2024-10-01 08:57 UTC, mudrila commented on src/app/app/page.tsx
> +  return <BudgetAccountForm />;
Instead - please revert this change and move `BudgetAccountForm` usage to the `BudgetPage`

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +          <Button type="submit">Create</Button>
Let's make it `variant="contained"`

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +          <Button onClick={handleClose}>Cancel</Button>
Let's make it `variant="outlined"` and also `type="reset"` to clear up the form

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +        Create Account
Let's be explicit here - `Create Budget Account`
And also let's add Plus icon after the text through `endIcon` prop

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +        Create Account
https://mui.com/material-ui/react-button/#buttons-with-icons-and-label

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +          <TextField
For this one - let's replicate following UI/UX
https://mui.com/material-ui/material-icons/#search-material-icons
The only thing is that it should show nested modal with icon selection.
The value supplied should be an unique ID of the icon, from which we could easily identify which icon should be shown in the UI

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +      <Dialog
Please, make sure this dialog takes full screen width below `md` resolution

2024-10-01 08:57 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +      <Dialog
At the same time - above `md` it should be statically `600px` width

2024-10-01 12:09 UTC, Artemh59 commented on src/constants/content.ts
> +export const accountTypes = ['Income', 'Debt', 'SpendingCategory', 'Credit', 'Debit'] as const;
idk I can't do it properly, it don't work with enum in route.ts
can I just add 'Goal'?

2024-10-01 16:26 UTC, mudrila requested changes
Almost there sir!
Apologies - haven't mentioned we would need virtualization to improve app performance while rendering large list of icons.
Also, we shouldn't be passing `userId` from FE to BE - it should be retrieved through `auth()` usage

2024-10-01 16:26 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +                {Object.keys(Icons).map(iconName => (
Oh yeah - we cannot render the whole damn thing at once - we need virtualization to prevent application lagging
Please add something like this: https://github.com/bvaughn/react-window

2024-10-01 16:26 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +          <TextField
Please, extract this icon selection into `IconSelect` component

2024-10-01 16:26 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +          userId,
We don't need to pass `userId` from here - we can read it within API route via `const session = await auth()` usage

2024-10-01 16:26 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +          userId,
And that will be safer - otherwise anyone could just create budget account via specifying someone's user ID

2024-10-01 16:27 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccount.tsx
> +          <TextField
We'll need to use virtualization in order to make it performant
I'd albeit from hand-picking icons at this stage - yes, it is reasonable in longer run - but I don't want us be spending time and picking/adjusting available icons each time we need it - just allow any icon and we'll introduce more tailored icon selection later on :)

2024-10-01 16:28 UTC, mudrila commented on src/constants/content.ts
> +export const accountTypes = ['Income', 'Debt', 'SpendingCategory', 'Credit', 'Debit'] as const;
Yeah, no worries - we'll figure this out later - minor nitpick

2024-10-01 16:29 UTC, mudrila commented on src/app/api/budgetAccount/create/route.ts
> +    const { title, description, icon, monthlyLimit, type, currentBalance, userId } =
So, instead of extracting `userId` from here - please add `const session = await auth()` usage and validate that session / user actually present - return error message in the response if that's not the case

2024-10-02 11:14 UTC, mudrila requested changes
Couple final nitpicks sir

2024-10-02 11:14 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +      <div style={{ ...style, display: 'flex', justifyContent: 'space-around' }}>
No explicit inline styling sir - please, transform this into `Box` element and pass `style={style}`
Unless it doesn't work that way - if so - let me know

2024-10-02 11:14 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +  const IconRow = ({ index, style }: { index: number; style: React.CSSProperties }) => {
Please extract it into separate file `src/components/molecules/IconSelect/IconSelect.tsx` and import from there

2024-10-02 11:14 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +  const renderIcon = (iconName: string) => {
Same with this function - put it there please and export

2024-10-02 11:14 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +  const renderIcon = (iconName: string) => {
Also would be better to transform it into component

```
function IconRenderrer({ iconName }: { iconName: string}) {
  const IconComponent = Icons[iconName as keyof typeof Icons];
  return IconComponent ? <IconComponent /> : null;
}
```

Will make react little bit more performant on working with DOM

2024-10-02 11:14 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +  const IconRow = ({ index, style }: { index: number; style: React.CSSProperties }) => {
`React.CSSProperties` -> `CSSProperties` and import that from `react`

2024-10-02 11:14 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +          <FormControl
Again - please, extract this `FormControl` into separate component under `src/components/molecules/IconSelect/IconSelect.tsx`

We're certainly will be re-using this component, but also this will make budget account form cleaner

2024-10-02 13:47 UTC, mudrila approved these changes

2024-10-02 13:47 UTC, merged