implement 'budgetAccount' entities displaying
mudrila/fin-plan pull request #37
Opened 2024-10-02 14:56 UTC by Artemh59

Closes #30

2024-10-02 17:58 UTC, mudrila requested changes
Please, remove API route and client-side fetching of `budgetAccounts` - we should be fetching that during SSR

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#fetching-data-on-the-server-with-an-orm-or-database - here's an example on how to do that - ofc you need to apply our context (`prisma`, `session`, etc)

2024-10-02 17:58 UTC, mudrila commented on src/app/api/budgetAccount/get/route.ts
We don't need this API route - we can fetch directly from DB during server-side rendering

2024-10-02 17:58 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +  useEffect(() => {
Then again - we don't need this `useEffect`

2024-10-02 17:58 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +            <Box key={index}>
Please extract it into `BudgetAccountList` component and render it alongside with `BudgetAccountForm`, not within it.
Best path forward will be creating `src/components/pages/Budget/Budget.tsx` and then within that component

```
export default function Budget({ accounts }: { accounts: BudgetAccount[] }) {
  return (
    <Box>
      <Box sx={{ display: 'flex' ... }}>
        <Typography>Blah blah page title</Typography>
        <BudgetAccountForm />
      </Box>
      <Box sx={{ mt: 2 }}>
        <BudgetAccountSList accounts={accounts} />
      </Box>
  </Box>
  );
}
```

Obviously this is not complete implementation - but kinda an idea. Then you'll need to perform server-side rendering from the `src/app/budget/page.tsx`, fetch accounts and pass that in into newly create `Budget` component

2024-10-02 17:58 UTC, mudrila commented on src/app/components/molecules/IconSelect/IconSelect.tsx
> +export function IconRenderrer({ iconName }: { iconName: string }) {
Oh, good catch - haven't noticed it was within `IconSelect` previously.
Defining components shouldn't ever happen within another component - only outside as a separate high-level function

2024-10-03 12:02 UTC, mudrila requested changes
Bunch of suggestions / requests for improvements sir, but we're almost there :)

2024-10-03 12:02 UTC, mudrila commented on src/app/app/budget/page.tsx
> +async function getAccounts(): Promise<SerializedBudgetAccount[]> {
No need for this function extraction - SSR pages are good "containers" for such logic

2024-10-03 12:02 UTC, mudrila commented on src/app/app/budget/page.tsx
> +const convertDecimalToNumber = (account: BudgetAccount): SerializedBudgetAccount => ({
Please extract this into `src/utils/formatters.ts` and rename to `serializeBudgetAccount`

2024-10-03 12:02 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountForm.tsx
> +import { IconSelect } from '@/app/components/molecules/IconSelect/IconSelect';
Please convert `IconSelect` to be default export from `IconSelect.tsx` and revert this change

2024-10-03 12:02 UTC, mudrila commented on src/app/components/molecules/BudgetAccount/BudgetAccountList.tsx
> +    debtCreditDebitGoalAccounts: SerializedBudgetAccount[];
Then we wouldn't need `useState` / `useMemo` at all :)

2024-10-03 16:54 UTC, Artemh59 commented
I hope like this?)

2024-10-05 11:56 UTC, mudrila requested changes
Couple minor suggestions, then we'll be good to go sir.

2024-10-05 11:56 UTC, mudrila commented on src/app/components/pages/Budget/Budget.tsx
> +  const dBaccounts = await prisma.budgetAccount.findMany({
Very minor - I'd suggest renaming this just to `budgetAccounts`

2024-10-05 11:56 UTC, mudrila commented on src/app/components/pages/Budget/Budget.tsx
> +  const accounts = dBaccounts.map(serializeBudgetAccount);
And then this one to `serializedBudgetAccounts`

2024-10-05 11:56 UTC, mudrila commented on src/app/components/pages/Budget/Budget.tsx
> +    incomes: incomeAccounts,
You could align object prop names with variables names to leverage prop shorthand usage

```
  const incomes = accounts.filter(account => account.type === 'Income');
  const debits = accounts.filter(account => account.type === 'Debit');
  const credits = accounts.filter(account => account.type === 'Credit');
  const debts = accounts.filter(account => account.type === 'Debt');
  const goals = accounts.filter(account => account.type === 'Goal');
  const spendingCategories = accounts.filter(account => account.type === 'SpendingCategory');

const groupedAccounts = { incomes, debits, credits, goals, spendingCategories }
```

2024-10-05 11:56 UTC, mudrila commented on src/app/components/pages/Budget/Budget.tsx
> +  const session = await auth();
I'd personally prefer to see all this logic in `src/app/app/budget/page.tsx` to kinda separate concerns. Data fetching mostly should be happening within `Next.js`-specific components, while displaying and interacting - within UI components. WDYT about such approach?

2024-10-05 11:56 UTC, mudrila commented on src/app/components/pages/Budget/Budget.tsx
> +export default async function Budget() {
If we'd follow approach that I'm suggesting - we could remove `async` here and make this component being rendered statically - as opposed to having to `async` components currently

2024-10-05 12:16 UTC, Artemh59 commented on src/app/components/pages/Budget/Budget.tsx
> +  const session = await auth();
Good approach, I will stick to it in future

2024-10-05 15:57 UTC, mudrila approved these changes
LFG 🚀

2024-10-05 15:57 UTC, merged