implement user account page
mudrila/fin-plan pull request #51
Opened 2024-10-07 17:27 UTC by Artemh59

Closes #44

2024-10-07 18:59 UTC, mudrila requested changes
Few minor changes but should be good to go then

2024-10-07 18:59 UTC, mudrila commented on src/app/api/user/[id]/route.ts
> +    if (!userId) {
Think this might be even before `try..catch` block

2024-10-07 18:59 UTC, mudrila commented on src/app/api/user/[id]/route.ts
> +export async function PUT(request: Request, { params }: { params: { id: string } }) {
Oh, I just realized - we don't need to put it under `/api/user/[id]` - could be just `/api/account` and working with `userId` that is supplied from session, no need for `params.id`

2024-10-07 18:59 UTC, mudrila commented on src/app/api/user/[id]/route.ts
> +    if (Object.keys(updateData).length === 0) {
Let's put it before very first `if(name)` - `if (!name || !email || !password || !image) ... `

2024-10-07 18:59 UTC, mudrila commented on src/app/app/user/page.tsx
> +  title: `User page | ${APP_SHORT_NAME}`,
Let's call it `Your Account` instead and move it to `src/app/app/account`

2024-10-07 18:59 UTC, mudrila commented on src/components/molecules/Header/Header.tsx
> +          <StyledLink href="/app/user">Hello, {session.data?.user?.name}</StyledLink>
Let's change it to `MenuItem`, put there "manage account icon"

```
import ManageAccountsIcon from '@mui/icons-material/ManageAccounts';
```

2024-10-07 18:59 UTC, mudrila commented on src/components/pages/User/Profile.tsx
> +export default function Profile({ userName, userId }: ProfileProps) {
Let's call it `Account`

2024-10-07 19:41 UTC, Artemh59 commented on src/app/api/user/[id]/route.ts
> +    if (!userId) {
Do I need to rewrite it everywhere in this commit?

2024-10-07 19:45 UTC, Artemh59 commented
and when we change some user's information, we don't see it on page, to see this we need to logout and again login, but in database everything change on time, how we can fix it?

2024-10-16 21:33 UTC, mudrila commented on src/app/api/user/[id]/route.ts
> +    if (!userId) {
Yes please

2024-10-16 21:35 UTC, mudrila commented
> and when we change some user's information, we don't see it on page, to see this we need to logout and again login, but in database everything change on time, how we can fix it?

So, for that - we'll need to adjust the way we're reading / writing to `jwt` and `session` on initializing `next-auth`. I do have a clear picture for fixing / implementing this - but let's tackle it later

2024-10-16 21:40 UTC, mudrila requested changes
Bunch of changes, but should be good to go then!

2024-10-16 21:40 UTC, mudrila commented on src/app/app/account/page.tsx
> +    return <Profile userName={userName} />;
Well, given we do require `userName` during profile creation - it is safe to assume that if it's not set in session - `user` is not authorized at all. Though user won't get here due to `middleware.ts` validation - to provide better type compatibility and logic handling - let's flip this condition 
```
if (session?.user) {
  redirect('/sign-in')
}

return <Profile userName={userName}
```

2024-10-16 21:40 UTC, mudrila commented on src/components/pages/User/Account.tsx
> +  const [image, setImage] = useState<File>();
We should pre-fill it from user's session information

2024-10-16 21:40 UTC, mudrila commented on src/components/pages/User/Account.tsx
> +  const [name, setName] = useState('');
And here

2024-10-16 21:40 UTC, mudrila commented on src/components/pages/User/Account.tsx
> +  const [email, setEmail] = useState('');
And here

2024-11-06 21:59 UTC, mudrila approved these changes

2024-11-06 22:00 UTC, merged