Implement 'forgot password' functionality
mudrila/fin-plan pull request #56
Opened 2024-11-11 11:48 UTC by Artemh59

Closes #36

2024-11-11 14:30 UTC, mudrila requested changes
Amazing work, sir!
Have some suggestions, but overall - looks really great!

2024-11-11 14:30 UTC, mudrila commented on src/app/api/auth/forgot-password/route.ts
> +    return NextResponse.json({ message: 'Code sended!' });
Code sended -> Code sent

2024-11-11 14:30 UTC, mudrila commented on src/app/api/auth/forgot-password/route.ts
> +      text: otpCode,
Let's make it `Your verification code: ${otpCode}`

2024-11-11 14:30 UTC, mudrila commented on src/app/api/auth/forgot-password/route.ts
> +      subject: 'Verification Code',
Let's change it to `Resetting your password at YFP: Verification Code`

2024-11-11 14:30 UTC, mudrila commented on src/app/api/auth/reset-password/route.ts
> +        return NextResponse.json({ message: 'Please check our password' });
Let's change this message to `Password doesn't match required security parameters`

2024-11-11 14:30 UTC, mudrila commented on src/app/api/auth/reset-password/route.ts
> +      return NextResponse.json({ message: 'Please enter password' });
`New password wasn't sent`

2024-11-11 14:30 UTC, mudrila commented on src/app/api/auth/reset-password/route.ts
> +      return NextResponse.json({ errorMessage: 'please check our data' });
`Verification token wasn't found or expired`

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +      audienceId: '274752ed-c875-4c06-aa9e-984d5b96df11',
We'll surely be operating with this `audienceId` - let's move it somewhere to constants / config

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +      email: email,
Can use prop shorthand here, instead of `email: email` -> `email,`

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +    const resend = new Resend(process.env.RESEND_API_KEY);
Let's throw an error if `process.env.RESEND_API_KEY` is not set
And also - please, add `RESEND_API_KEY` to the `.env.example`

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +    const userAccountId = (await contact).data?.id;
Instead of this - please add `await` before `resend.contacts.create`
Also, if it wasn't created - let's return an error

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +          providerId: 'email-and-password',
Let's move this into some constant and reuse between auth and this place

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +          providerType: 'CredantialsProvider',
Same for this

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +      return NextResponse.json({ errorMassage: 'Please check our creadentials' });
`Required data is missing from the request payload`
Nevertheless we're building API routes right within our FE repository - they're still API routes and we should treat each client request as "unknown client"

2024-11-11 14:30 UTC, mudrila commented on src/app/api/send/route.ts
> +    return NextResponse.json({ message: 'Added to audience!' });
I'd prefer something like `Your email successfully subscribed for most necessary security updates!

2024-11-11 14:30 UTC, mudrila commented on src/components/molecules/Inputs/OTPInput/OTPInput.tsx
> +export function OTPInput({ email }: OTPInputProps) {
Let's try to simplify this component and leverage existing library:

https://github.com/viclafouch/mui-otp-input

If that doesn't work - then let's keep going with our own component

2024-11-11 14:30 UTC, mudrila commented on src/components/organisms/Forms/ForgotPasswordForm/ForgotPasswordForm.tsx
> +              // disabled={loading}
Let's keep it disabled when we're loading :)

2024-11-11 14:30 UTC, mudrila commented on src/components/organisms/Forms/ForgotPasswordForm/ForgotPasswordForm.tsx
> +  const handleSubmit = async (event: React.FormEvent) => {
`React.FormEvent` -> `FormEvent`

2024-11-11 14:30 UTC, mudrila commented on src/components/organisms/Forms/ForgotPasswordForm/ForgotPasswordForm.tsx
> +import { OTPInput } from '../../../molecules/Inputs/OTPInput/OTPInput';
Please use import aliases to keep stuff consistent :)

2024-11-11 14:30 UTC, mudrila commented on src/components/organisms/Forms/SignInForm/SignInForm.tsx
> +          <Link
I think we have something like `StyledNextLink` with pretty much these exact styles? Can we use it here?

2024-11-11 14:30 UTC, mudrila commented on src/components/organisms/Forms/SignUpForm/SignUpForm.tsx
> +            await signIn('email-and-password', {
Also can reuse that provider ID here

2024-11-11 14:30 UTC, mudrila commented on src/components/organisms/Forms/SignUpForm/SignUpForm.tsx
> +            toast.success('Signed Up! You will be redirected to app in a blink of an eye');
Seems like I accidentally killed the logic for replacing existing tooltip and now it just throws more toasts. Please, revive that logic sir

2024-11-11 15:55 UTC, Artemh59 commented on src/components/molecules/Inputs/OTPInput/OTPInput.tsx
> +export function OTPInput({ email }: OTPInputProps) {
it works, but I have only 4 boxes and can't find info how change it

2024-11-11 16:16 UTC, Artemh59 commented on src/components/organisms/Forms/SignUpForm/SignUpForm.tsx
> +            toast.success('Signed Up! You will be redirected to app in a blink of an eye');
idk, I tested it and everything  works normally

2024-11-11 16:23 UTC, Artemh59 commented on src/components/molecules/Inputs/OTPInput/OTPInput.tsx
> +export function OTPInput({ email }: OTPInputProps) {
Now it doesn't  work

2024-11-11 21:35 UTC, mudrila commented on src/components/molecules/Inputs/OTPInput/OTPInput.tsx
> +export function OTPInput({ email }: OTPInputProps) {
Yeah, OK, let's stick to existing component
Lol, not allowing for more than 4 digits sounds ridiculous

2024-11-11 21:36 UTC, mudrila commented on src/components/organisms/Forms/SignUpForm/SignUpForm.tsx
> +            toast.success('Signed Up! You will be redirected to app in a blink of an eye');
Oke, than ignore this comment sir

2024-11-11 21:44 UTC, mudrila requested changes
Moar changes sir

2024-11-11 21:44 UTC, mudrila commented on package.json
> -    "@types/react": "npm:types-react@19.0.0-rc.0",
Nope - revert this change pls

2024-11-11 21:44 UTC, mudrila commented on package.json
> +    "mui-one-time-password-input": "^3.0.1",
So, if having 6 digits doesn't work with this lib - please, remove it from dependencies

2024-11-11 21:44 UTC, mudrila commented on package.json
> +    "@types/react-dom": "^18.3.1",
Same here - we wanna have `react-dom` at version 19

2024-11-11 21:44 UTC, mudrila commented on src/app/api/auth/forgot-password/route.ts
> +    const resend = new Resend(process.env.RESEND_API_KEY);
Still not seeing `if (!process.env.RESEND_API_KEY) { throw new Error('Fuck you!') }`

2024-11-11 21:44 UTC, mudrila commented on src/app/api/auth/forgot-password/route.ts
> +      const digits = '0123456789';
Please, extract this to utility function

2024-11-11 21:44 UTC, mudrila commented on src/app/api/auth/forgot-password/route.ts
> +export async function PUT(request: Request) {
This should be not `PUT` but `GET` instead

2024-11-11 21:44 UTC, mudrila commented on src/app/api/auth/reset-password/route.ts
> +    await prisma.user.update({
Also, please delete verification token to prevent double-usage

2024-11-11 21:44 UTC, mudrila commented on src/components/organisms/Forms/SignInForm/SignInForm.tsx
> +              color: 'inherit',
Now, seems like we don't need all these `style={...}`
Also, please - don't use inline styling

2024-11-12 11:49 UTC, Artemh59 commented on src/app/api/auth/forgot-password/route.ts
> +export async function PUT(request: Request) {
but we need to receive  'otp' from user or we'll do it like this: '/api/auth/forgot-password?otp=..&email=...'?

2024-11-14 00:19 UTC, Artemh59 commented
Now must be good)

2024-11-14 10:40 UTC, mudrila commented on src/constants/content.ts
> +export const lightBackground = 'rgba(255, 255, 255, 0.9)';
Let's call it something little more explicit - this is used for cards / papers, right? Then let's rename it to `paperLightGrayBackground`

2024-11-14 10:41 UTC, mudrila commented on src/constants/content.ts
> +export const darkBackground = 'rgba(18, 18, 18, 0.8)';
And this one - `paperDarkBackground`
And also - let's move these colors exports into `src/theme/tokens.ts` - this will be a temporary measure until we'll refactor theme creation to incorporate these tokens right into theme

2024-11-14 10:43 UTC, mudrila requested changes
Also couple dependencies cleanup, pls

2024-11-14 13:02 UTC, mudrila approved these changes

2024-11-14 13:02 UTC, merged