Split budget account entity into multiple entities
mudrila/fin-plan pull request #67
Opened 2024-11-18 12:50 UTC by Artemh59

Closes #59

2024-11-20 20:18 UTC, mudrila requested changes
Plenty of changes, sir
But mostly about cleaning things up
I'd also like to see more DRY whenever it's possible - we can always split components, but it will get harder and harder to join them if we'd figure out we don't actually need all of them

2024-11-20 20:18 UTC, mudrila commented on prisma/schema.prisma
> +  SpendingCategories           SpendingCategory[]
Let's change it to `spendingCategories`

2024-11-20 20:18 UTC, mudrila commented on prisma/schema.prisma
> +  Goals                        Goals[]
Same here

2024-11-20 20:18 UTC, mudrila commented on prisma/schema.prisma
> +  GoalTransacions              GoalTransaction[]
And here

2024-11-20 20:18 UTC, mudrila commented on prisma/schema.prisma
> +model Goals {
`model Goal`

2024-11-20 20:18 UTC, mudrila commented on prisma/schema.prisma
> +  transacions IncomeSource @relation("Transactions", fields: [fromIncomeSourceId], references: [id], onDelete: Cascade)
`transactions`

2024-11-20 20:18 UTC, mudrila commented on prisma/schema.prisma
> +  transacions SpendingCategory @relation("Transactions", fields: [transactionsTo], references: [id], onDelete: Cascade)
Same here

2024-11-20 20:18 UTC, mudrila commented on src/app/api/goalAccount/[id]/route.ts
Let's change folder name: `goalAccount` -> `goal`

2024-11-20 20:18 UTC, mudrila commented on src/app/api/incomeAccount/route.ts
Let's change from `incomeAccount` -> `income`

2024-11-20 20:18 UTC, mudrila commented on src/utils/getBudgetAccountInfo.ts
> +export async function updateBudgetTransaction(transactions: BudgetAccountTransaction[]) {
Let's rename this function from `updateBudgetTransaction` to `mapBudgetTransaction`

2024-11-20 20:18 UTC, mudrila commented on src/utils/getBudgetAccountInfo.ts
> +export async function updateIncomeTransaction(transactions: IncomeSourceTransaction[]) {
Same: `update` -> `map`

2024-11-20 20:18 UTC, mudrila commented on src/utils/getBudgetAccountInfo.ts
> +export async function updateGoalTransaction(transactions: GoalTransaction[]) {
Same here

2024-11-20 20:18 UTC, mudrila commented on src/utils/getBudgetAccountInfo.ts
> +export async function updateSpendTransaction(transactions: SpendingCategoryTransaction[]) {
Same here

2024-11-20 20:18 UTC, mudrila commented on src/utils/getBudgetAccountInfo.ts
>    const updatedTransaction = await Promise.all(
Same applies for the variable names `updated` -> `mapped`

2024-11-20 20:18 UTC, mudrila commented on src/types/budget.ts
> +  type: string;
I think this should be `Income` to explicitly mark that typed income account can only have `type: 'Income'`

2024-11-20 20:18 UTC, mudrila commented on src/types/budget.ts
> +  type: string;
Same here probably

2024-11-20 20:18 UTC, mudrila commented on src/types/budget.ts
> +  type: string;
Same here

2024-11-20 20:18 UTC, mudrila commented on src/constants/content.ts
> +export const accountTypes = ['Debt', 'Credit', 'Debit'] as const;
`accountTypes` -> `budgetAccountTypes`

2024-11-20 20:18 UTC, mudrila commented on src/components/pages/Budget/Budget.tsx
> +export default function Accounts({
This is still `Budget` page, ser

2024-11-20 20:18 UTC, mudrila commented on src/components/pages/Budget/Budget.tsx
> +interface AccountsProps {
Same here

2024-11-20 20:18 UTC, mudrila commented on src/components/molecules/Accounts/SpendingCategoryAccounts/SpendingCategoryAccountList.tsx
> +  SpendingCategoryAccounts,
So this will be lower case

2024-11-20 20:18 UTC, mudrila commented on src/components/molecules/Accounts/SpendingCategoryAccounts/SpendingCategoryAccountList.tsx
> +  SpendingCategoryAccounts: SpendingCategory[];
And this

2024-11-20 20:18 UTC, mudrila commented on src/components/molecules/Accounts/GoalAccounts/GoalAccountList.tsx
> +interface incomeAccountListProps {
`incomeAccountListProps` -> `IncomeAccountsListProps`

2024-11-20 20:18 UTC, mudrila commented on src/components/molecules/Accounts/GoalAccounts/GoalAccountList.tsx
> +export default function GoalAccountList({ goalAccounts }: incomeAccountListProps) {
`GoalsList`

2024-11-20 20:18 UTC, mudrila commented on src/components/molecules/Accounts/GoalAccounts/GoalAccountList.tsx
> +  goalAccounts: SerializedGoalAccount[];
`goals: SerializedGoal[]`

2024-11-20 20:18 UTC, mudrila commented on src/app/app/page.tsx
> +  const changedBudgetTransactions = await updateBudgetTransaction(budgetTransactions);
So this should b` mappedBudgetAccountTransactions`

2024-11-20 20:18 UTC, mudrila commented on src/app/app/page.tsx
> +  const changedIncomeTransactions = await updateIncomeTransaction(incomeTransactions);
`mappedIncomeTransactions`

2024-11-20 20:18 UTC, mudrila commented on src/app/app/page.tsx
> +  const changedGoalTransactions = await updateGoalTransaction(goalTransactions);
And so on...

2024-11-20 20:18 UTC, mudrila commented on src/app/app/page.tsx
> +        ...changedBudgetTransactions,
I think we also wanna sort them by date, latest first

2024-11-20 20:18 UTC, mudrila commented on src/app/app/page.tsx
> +  const budgetTransactions = await prisma.budgetAccountTransaction.findMany({
We'll have to do `join` later - will be much faster than 4 requests
But don't worry right now - we'll take care about it later :)

2024-11-20 20:18 UTC, mudrila commented on src/app/app/budget/page.tsx
> +  title: `Accounts | ${APP_SHORT_NAME}`,
Still `Budget` page, ser

2024-11-20 20:18 UTC, mudrila commented on src/app/app/budget/page.tsx
> +export default async function AccountsPage() {
Same here

2024-11-20 20:35 UTC, Artemh59 commented
Yes of course, I will do it more DRY, but as I said, I wasn't sure that I did everything right. I'll do it tomorrow

2024-11-26 20:09 UTC, mudrila approved these changes
LFG

2024-11-26 20:09 UTC, merged